"""Integration shared constants."""

import logging

SINKS = "SCREAM-ROUTER-SINKS"
SOURCES = "SCREAM-ROUTER-SOURCES"
ROUTES = "SCREAM-ROUTER-ROUTES"
DATA_AVAILABLE = "available"
DEFAULT_NAME = "SCREAM-ROUTER"
DEFAULT_PORT = 8080
DOMAIN = "scream_router"
LOGGER = logging.getLogger(__package__)
SCREAM_ROUTER_SERVER = "SCREAM-ROUTER-SERVER"
